### ISSUE TITLE
Unable to Download Imported Carousel Files - NS_BINDING_ABORTED and 500 Internal Server Errors

### ISSUE THREAD

**Issue by francescofeston** [FranciscoMoretti/carousel-generator#10]
Hi @FranciscoMoretti.

**Description:**
I am experiencing issues when attempting to download imported content (custom JSON) through my carousel generator project. While the default model files can be downloaded successfully, when I import my own content, the download process fails. In particular, I'm seeing multiple `NS_BINDING_ABORTED` and `500 Internal Server Error` responses in the browser console logs.

This issue arises when my proxy server attempts to fetch external resources such as images, which leads to the 500 errors. Here are the details:

---

**Steps to Reproduce:**
1. Use the default carousel model - files download successfully.
2. Import custom content in JSON format to generate a new carousel.
3. Attempt to download the generated files.
4. Observe that the download fails with network errors.

---

**Expected Behavior:**
The custom imported content should generate the carousel correctly and allow the download of the generated files.

---

**Actual Behavior:**
- Download fails with `NS_BINDING_ABORTED` and `500 Internal Server Error` messages.
- The custom content does not download successfully after import.

---

**Error Logs from Browser Console:**
```plaintext
GET https://example.com/background1.jpg NS_BINDING_ABORTED
GET http://localhost:3000/api/proxy?url=https://example.com/background1.jpg [HTTP/1.1 500 Internal Server Error 1258ms]
GET https://example.com/avatar.png NS_BINDING_ABORTED
GET http://localhost:3000/api/proxy?url=https://example.com/avatar.png [HTTP/1.1 500 Internal Server Error 1266ms]
```

---

**Environment:**
- **Platform:** Local development environment (`localhost:3000`)
- **Deployment:** Vercel
- **Browser:** Chrome, latest version
- **API Setup:** Using a proxy to fetch external resources (e.g., images)

---

**Additional Context:**
It seems that the issue is related to the proxy server setup when fetching external resources (e.g., images). The default model doesn't have these issues, but custom JSON imports fail during the download process. 

I would appreciate any guidance or recommendations to resolve this issue, especially regarding proxy server configuration and error handling for external resources.

Thank you!

---

**Comment by FranciscoMoretti** [comment]
This is likely related to the images addresses in particular. 

Can you share the image links you used? 

Can you also share the content JSON file?

I'd like to reproduce it.

Context: There is no difference between URL input and JSON import. I think the proxy is trying to get an image from a site that doesn't serve images.

**Comment by francescofeston** [comment]
Hi @FranciscoMoretti,

image links: https://example.com/background1.jp; https://example.com/background2.jp; https://example.com/background3.jp and so on.

JSON file attached. 
[test_two.json](https://github.com/user-attachments/files/17242386/test_two.json)

Thanks,
Francesco

**Comment by FranciscoMoretti** [comment]
Those image links (and the ones in the json file) return `404` when I access with my browser.

Here is an example of your JSON with some sample images from https://picsum.photos/

[test_two.json](https://github.com/user-attachments/files/17255948/test_two.json)
