### ISSUE TITLE
Failed to autogenerate vi own OpenAI API key

### ISSUE THREAD

**Issue by top-rated** [FranciscoMoretti/carousel-generator#7]
Hi @Francisco. Thanks for your awesome tool! I can see that your preview is using AI gen feature, but I failed to setup it up on my self hosted version. I've added my OpenAI API Key (tried both User API Keys and Project Keys) literally everywhere...) Kindly advise please. Regards, Dan.

**Comment by FranciscoMoretti** [comment]
Hi Dan, thanks for creating this issue.

Can you share screenshots of errors you might be getting in the server (where you do `npm run dev`) and in the client (browser console)?

**Comment by top-rated** [comment]
Thanks so much for getting back to me, @FranciscoMoretti! Really appreciate it. I've temporary destroyed my build, and so far using the free hobby Vercel plan (didn't know about it before, so thanks for it as well). My purpose is to add my OpenAI API key, but to limit it to a certain amount of requests I could manage according to subscription and/or pay as you go plan. Just to mention, I'm not exactly trying to monetise your solution, but would really love to add it to my LinkedIn tools bundle I have for my current and prospecting clients. So ideally it would be like SaaS with the paywall i have for it. Or at least for some private community of freelancers like I am. Thank you in advance! Regards, Dan.

**Comment by FranciscoMoretti** [comment]
@top-rated I've realized that `KV_REST_API_URL` and `KV_REST_API_TOKEN` said optional, but they weren't. I've just pushed a change to make them optional.

Additionally, I've added a step to the installation instructions with a few more details regarding environment variables.

BTW: This project is MIT licensed, so feel free to use it

Thanks for the feedback!

**Comment by FranciscoMoretti** [comment]
I'll close this as resolved, feel free to open again if you find a issue after the changes
