### ISSUE TITLE
Carousel Generator not importing json files

### ISSUE THREAD

**Issue by francescofeston** [FranciscoMoretti/carousel-generator#9]
Description: I am having trouble importing a JSON file into my project. The current implementation and proposed solutions for file import are not working as expected, and I keep encountering errors.

Details:

    Error: I consistently receive errors like:

    ZodError: Expected array, received object

    I have tried wrapping the JSON data in an array as suggested, but this has not resolved the issue.

Steps to Reproduce:

    I am using a file input to import a JSON file into the application.
    The JSON structure follows the schema defined in the project, but I get Zod validation errors.
  
What I've Tried:

    Wrapping the JSON content in an array.
    Ensuring that the JSON structure matches the Zod schema (checked brand, theme, fonts, pageNumber fields).

Expected Behavior: The JSON file should be parsed correctly, and the imported data should match the defined Zod schema.

Actual Behavior: The JSON fails validation, showing Zod errors that indicate the schema expects an array, but the input is being recognized as an object, despite the JSON structure being correctly formatted.

JSON File Example: Here is an example of the JSON structure I am using:

json

[
  {
    "brand": {
      "avatar": {
        "type": "Image",
        "source": {
          "type": "UPLOAD",
          "src": "https://example.com/avatar.png"
        },
        "style": {
          "opacity": 100
        }
      },
      "name": "Example Brand",
      "handle": "@examplehandle"
    },
    "theme": {
      "primaryColor": "#ff0000",
      "secondaryColor": "#00ff00",
      "backgroundColor": "#ffffff",
      "isCustom": true,
      "palette": "custom-palette"
    },
    "fonts": {
      "bodyFont": "Arial",
      "headingFont": "Helvetica"
    },
    "pageNumber": {
      "showPageNumber": true,
      "position": "bottom-right"
    }
  }
]

Request: Could you help me understand what might be causing the import to fail, and provide guidance on the correct way to import JSON data into the application? Any further insights or suggestions for troubleshooting this issue would be appreciated.
Thanks

**Comment by FranciscoMoretti** [comment]
Hi @francescofeston, 

Some of the fields in your json are not recognized by the settings schema

I suggest you start from an exported settings json and change the values.

Here is the default one

```json
{
    "brand": {
        "avatar": {
            "type": "Image",
            "source": {
          "type": "UPLOAD",
          "src": "https://example.com/avatar.png"
            },
            "style": {
                "opacity": 100
            }
        },
        "name": "My name",
        "handle": "@name"
    },
    "theme": {
        "primary": "#ff865b",
        "secondary": "#caccce",
        "background": "#121c22",
        "isCustom": false,
        "pallette": "sunset"
    },
    "fonts": {
        "font1": "DM_Serif_Display",
        "font2": "DM_Sans"
    },
    "pageNumber": {
        "showNumbers": true
    }
}
```

**Comment by francescofeston** [comment]
Hi @FranciscoMoretti,

Thank you for your feedback. 
I tried to use the default schema and the error persists (please have a look at the screenshot below).

![immagine](https://github.com/user-attachments/assets/8582fb39-99ce-492c-9b9e-d4b2ca0ea003)

May this be due to the errors I came across upon installing npm?

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: carousel-generator@0.1.0
npm error Found: tailwindcss@0.0.0-insiders.87d7b91
npm error node_modules/tailwindcss
npm error   tailwindcss@"0.0.0-insiders.87d7b91" from the root project
npm error
npm error Could not resolve dependency:
npm error peer tailwindcss@">=3.0.0 || insiders" from tailwindcss-animate@1.0.7
npm error node_modules/tailwindcss-animate
npm error   tailwindcss-animate@"^1.0.7" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\Utente\AppData\Local\npm-cache\_logs\2024-09-27T10_52_11_597Z-eresolve-report.txt

Then I ran npm install --force and apparently it worked, The json file cannot be imported though, 
Thanks again for your help.

Francessco

**Comment by FranciscoMoretti** [comment]
It seems you are trying to "Import content" instead of settings. 

In that case, you can start by exporting the content.


https://github.com/user-attachments/assets/81e9c185-b68a-4c8b-9218-01a53ab3c928

Additionally, you can use the deployed address to verify if this is an error with your installation or with the project https://carouselgenerator.vercel.app/

I'm taking a look into supporting npm without errors

**Comment by FranciscoMoretti** [comment]
I simplified dependencies a bit and pushed an update. You should be able to install with `npm` without needing to use the `--force` flag

**Comment by francescofeston** [comment]
It now works like magic. Thanks a lot @FranciscoMoretti 
Congrats on this project!
Cheers,
francesco

**Comment by francescofeston** [comment]
@FranciscoMoretti 

apologies for bothering again. 
There seems to be a minor bug upon downloading the carousel file. The default file can be dowloaded without issues. When I try to download my own though, it does not work.

Thank you having a look at it and letting me know. 
francesco
